/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include <stdint.h>

#include "main.h"

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClkCtrReg = (RCC_AHB1ENR_t *) 0x40023830;
	GPIOx_MODE_t  volatile *const pPortDModeReg = (GPIOx_MODE_t *) 0x40020C00;
	GPIOx_ODR_t   volatile *const pPortDoutReg = (GPIOx_ODR_t *) 0x40020C14;

	//enable the clock for GPIO port D
	pClkCtrReg->gpioa_en=1;

	//configure the mode of IO pin as output
	pPortDModeReg->pin_5=1;

	while(1)
		{
			//set the 12th bit of the output data register to make I/O pin-12 as high
			pPortDoutReg->pin_5=1;

			//delay
			for(uint32_t i=0; i<30000;i++)
			{

			}

			//clear the 12th bit of the output data register to make I/O pin-12 as low
			pPortDoutReg->pin_5=0;

			//delay
			for(uint32_t i=0; i<30000;i++)
			{

			}
		}
}
